spring:
  application:
    name: stockmarketsimulator
  profiles:
    active: ${ACTIVE_PROFILE:local}
#  main.allow-bean-definition-overriding: true

finnhub:
  base-url: ${FINNHUB_BASE_URL:"https://finnhub.io/api/"}
  auth-header: ${FINNHUB_AUTH_HEADER:"X-Finnhub-Token"}
  api-version: ${FINNHUB_API_VERSION:"v1"}
  api-key: ${FINNHUB_API_KEY}

executor:
  stock:
    period: ${PERIOD_STOCK_STOCK_EXECUTOR:86400000}
    time-unit: ${TIME_UNIT_STOCK_EXECUTOR:MILLISECONDS}
