spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USR}
    password: ${POSTGRES_PWD}

  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update

executor:
  stock:
    scheduled:
      rest:
        initial-delay: ${STOCK_EXECUTOR_INITIAL_DELAY:60000}
#  output:
#    ansi:
#      enabled: always

  # main:
    # log-startup-info: false
