spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USR}
    password: ${POSTGRES_PWD}
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop