spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USR}
    password: ${POSTGRES_PWD}

  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update

executor:
  stock:
    scheduled:
      rest:
        initial-delay: ${STOCK_EXEC_INIT_DELAY:60000}
  quote:
    scheduled:
      websocket:
        initial-delay: "${QUOTE_SCHED_EXEC_WS_INIT_DELAY:60}"
  candle:
    scheduled:
      initial-delay: "${CANDLE_SCHED_EXEC_INIT_DELAY:5000}"
#  output:
#    ansi:
#      enabled: always

  # main:
    # log-startup-info: false
