spring:
  application:
    name: stockmarketsimulator
  profiles:
    active: "${ACTIVE_PROFILE:local}"
#  main.allow-bean-definition-overriding: true

finnhub:
  api-key: "${FINNHUB_API_KEY}"
  rest:
    base-url: "${FINNHUB_REST_BASE_URL:https://finnhub.io/api/}"
    auth-header: "${FINNHUB_REST_AUTH_HEADER:X-Finnhub-Token}"
    api-version: "${FINNHUB_REST_API_VERSION:v1}"
  websocket:
    uri: "${FINNHUB_WS_URI:wss://ws.finnhub.io}"
    auth-query-param: "${FINNHUB_WS_AUTH_PARAM:token}"
    timeout: "${FINNHUB_WS_TIMEOUT:2}"
    timeout-unit: "${FINNHUB_WS_TIMEOUT_UNIT:SECONDS}"

executor:
  stock:
    scheduled:
      rest:
        pool-size: "${STOCK_SCHED_EXEC_REST_POOL_SIZE:1}"
        period: "${STOCK_SCHED_EXEC_REST_PERIOD:86400000}"
        unit: "${STOCK_SCHED_EXEC_REST_UNIT:MILLISECONDS}"
  quote:
    pool-size: "${QUOTE_EXEC_POOL_SIZE:1}"
    queue-bound: "${QUOTE_EXEC_QUEUE_BOUND:10}"
    alive-time: "${QUOTE_EXEC_ALIVE_TIME:300}"
    alive-unit: "${QUOTE_EXEC_ALIVE_UNIT:SECONDS}"
    scheduled:
      websocket:
        pool-size: "${QUOTE_SCHED_EXEC_WS_POOL_SIZE:2}"
        unit: "${QUOTE_SCHED_EXEC_WS_UNIT:SECONDS}"
        session-duration: "${QUOTE_SCHED_EXEC_WS_SESSION_DURATION:45}"
        session-unit: "${QUOTE_SCHED_EXEC_WS_SESSION_UNIT:SECONDS}"
        grace-period: "${QUOTE_SCHED_EXEC_WS_GRACE_PERIOD:10}"
        grace-unit: "${QUOTE_SCHED_EXEC_WS_GRACE_UNIT:SECONDS}"
        batch-size: "${QUOTE_SCHED_EXEC_WS_BATCH_SIZE:30}"
        batch-delay: "${QUOTE_SCHED_EXEC_WS_BATCH_DELAY:60}"
        batch-unit: "${QUOTE_SCHED_EXEC_WS_BATCH_UNIT:SECONDS}"